# Generated by Django 3.1.7 on 2021-02-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addevent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_event',
            name='time',
            field=models.DateTimeField(blank=True),
        ),
    ]
