# Generated by Django 3.1.7 on 2021-02-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addevent', '0002_auto_20210228_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_event',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
