# Generated by Django 3.1.7 on 2021-02-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addevent', '0003_auto_20210228_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_event',
            name='time',
            field=models.CharField(max_length=76),
        ),
    ]
